### ISSUE TITLE
Individual Client Assignment when in Organisation

### ISSUE THREAD

**Issue by daniel-geerdink** [COS301-SE-2024/CoVAR#139]
If a user is part of an organisation they shouldn't be able to be assigned as an individual client.

**Comment by Aren-R** [comment]
Problem is in the request to fetch reports for a user. When a user is in an organisation it then fetches the organisations reports (not their individual ones). 

Either we allow individual reports for a client in an organisation or we dont allow VA's to be able to be assigned to / upload reports for individuals in an organisation
